### ISSUE TITLE
Installations that are no longer using Consul

### ISSUE THREAD

**Issue by andreslucena** [consuldemocracy/website#35]
Looking at your website, I found multiple markers that are wrong. I think that this for mainly two reasons: organizations that have migrated to other software and also organizations that could've showed interest on Consul in the past but finally are using an alternative. 

* Paris RIVP (France). In the map it has the link to https://budget-participatif.rivp.fr/budgets. That's a 404 to a Decidim installation 
* Tarragona (Spain). In the map it links to https://participa.tarragona.cat/. That's a Decidim installation 
* New York City (USA). In the map it has this URL https://pbnyc.participatorybudgeting.org/budgets. That's a 404. Their URL is https://www.participate.nyc.gov/ and it's a Decidim installation 
* Trondheim (Norway). In the map it says "Working", they're using Decidim: https://borgerkraft.no/?locale=en
* Gdynia (Polland). In the map it says "Working", they're using Decidim: https://konsultujemy.gdynia.pl/

**Comment by javierm** [comment]
Hi, @andreslucena :smile:.

Thanks for reporting! We've notified the person maintaining the map. We'll update this issue when we get confirmation that it's done.

By the way, best of luck with your project! We hope your situation is better than the one we went through a few years ago :smile:.

**Comment by andreslucena** [comment]
We'll see how it goes in a couple of months, fortunately we've been working on this scenario for some time now and we have financial support from other governments apart from Barcelona, as well as from our partners.

What is clear is that sustainability is a challenge for all of us, and we continue to look for ways to strengthen it.

**Comment by andreslucena** [comment]
Hi @javierm! I see that this is still not updated. Can you notify the person that's maintaining the map again please? Thanks

**Comment by javierm** [comment]
Hi, @andreslucena :smile:.

Sorry it isn't updated yet :pray:. We'll notify the people maintaining the map again once they're back from holidays.

By the way, in case you prefer to contact them directly (reporting here is fine, though :wink:), you can send an email to the address in the [contact section of the project's website](https://consuldemocracy.org/en/#contact).

**Comment by andreslucena** [comment]
Thank you for taking care of this @javierm!! I'll wait a couple of weeks and if I see that it stills unchanged I'll stop bothering you and send it directly to that email.

**Comment by javierm** [comment]
> I'll stop bothering you

No bother at all :wink:. Always great to hear from our fellow project :smile:.

**Comment by javierm** [comment]
Hi, @andreslucena :smile:.

In case you're interested, [the new "about us" page](https://consuldemocracy.org/about-us/) shows a map that differentiates between previous installations and active ones.

**Comment by andreslucena** [comment]
> In case you're interested, [the new "about us" page](https://consuldemocracy.org/about-us/) shows a map that differentiates between previous installations and active ones.

Hi @javierm

Great, that looks much better than the old page and map that you had.

We thought about doing something similar (showing old/discarded installations) but to be clear and not link to 404s, to link to the archive.org page instead. 

Related to that page "about us", there's an error in the explanation:

> The CONSUL DEMOCRACY software was developed by the municipality of Madrid in 2015. It was directly influenced by the country-wide Los Indignados and Democracia Real Ya! street protests in Spain of May 2015.

It should say

> The CONSUL DEMOCRACY software was developed by the municipality of Madrid in 2015. It was directly influenced by the country-wide Los Indignados and Democracia Real Ya! street protests in Spain of May **2011**. 

Also if this repository will not be updated/maintained anymore and doesn't correspond with the page (I see it's a wordpress), then I suggest to update the README and archive it. 

I'm closing this issue as the original report is already fixed.

**Comment by javierm** [comment]
Thanks for the comments! :pray: Didn't realize we weren't using this repository for the new site :sweat_smile:. I'll forward them to the team doing the website :+1:.
